/home/pi/trueface-py/main.py:35: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup (7,GPIO.OUT)
/home/pi/trueface-py/wiegand.py:13: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup (self.pin_D0,GPIO.OUT)
/home/pi/trueface-py/wiegand.py:14: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup (self.pin_D1,GPIO.OUT)
Traceback (most recent call last):
  File "/home/pi/trueface-py/main.py", line 315, in <module>
    app.run(host='0.0.0.0',port='5000', debug=False)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 1017, in run_sTraceback (most recent call last):
  File "/home/pi/trueface-py/main.py", line 239, in startCam
    wiegandOut.send(int(str(name["predicted_label"])),WIEGAND_BITS,USE_FACILITY)
ValueError: invalid literal for int() with base 10: 'Fernando C. Castro'
Traceback (most recent call last):
  File "/home/pi/trueface-py/main.py", line 239, in startCam
    wiegandOut.send(int(str(name["predicted_label"])),WIEGAND_BITS,USE_FACILITY)
ValueError: invalid literal for int() with base 10: 'Fernando C. Castro'
Traceback (most recent call last):
  File "/home/pi/trueface-py/main.py", line 239, in startCam
    wiegandOut.send(int(str(name["predicted_label"])),WIEGAND_BITS,USE_FACILITY)
ValueError: invalid literal for int() with base 10: 'Fernando C. Castro'
 already in use
[ WARN:0@2.215] global /tmp/pip-wheel-yqhq3sgl/opencv-contrib-python_c4e7c7ffd9b7480c9c72164eb700cd45/opencv/modules/videoio/src/cap_v4l.cpp (889) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
